title: "@blankapp/ui"
subtitle: "Highly customizable and theming components for React Native"
description: "Highly customizable and theming components for React Native"
author: JianyingLi <lijy91@foxmail.com>
language: en
timezone: UTC
url: https://blankapp.org
root: /
permalink: news/:year/:month/:day/:title/
archive_dir: news
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
per_page: 0

theme: navy

highlight:
  enable: true
  line_number: false

disqus_shortname: blankapp
google_analytics: UA-61561013-1
fb_admins:
# algolia:
#   en:
#     api_key:
#     index_name:
#   zh-Hans:
#     api_key:
#     index_name:
#   zh-Hant:
#     api_key:
#     index_name:
twitter: lijy91
github: blankapp/ui

deploy:
- type: git
  repo: git@github.com:blankapp/blankapp.github.io.git
- type: rsync
  host: blankapp.org
  user: root
  root: /root/sites/ui-homepage/html